# Generated by Django 5.2.17 on 2026-09-19 18:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='scrape_interval_hours',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('PRICE_INCREASE', 'PRICE_INCREASE'), ('PRICE_DECREASE', 'PRICE_DECREASE'), ('STOCK_INCREASE', 'STOCK_INCREASE'), ('STOCK_DECREASE', 'STOCK_DECREASE')], max_length=30)),
                ('previous_value', models.CharField(blank=True, max_length=100, null=True)),
                ('current_value', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tracked_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='tracker.trackedproduct')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('PRICE_DECREASE', 'PRICE_DECREASE'), ('PRICE_INCREASE', 'PRICE_INCREASE'), ('STOCK_DECREASE', 'STOCK_DECREASE'), ('STOCK_INCREASE', 'STOCK_INCREASE')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracked_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracker.trackedproduct')),
                ('change_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracker.productchange')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
